name: remote ssh command
on: 
    push:
        branches:
        - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: "cd muusik-api && sudo git pull && /home/ubuntu/.nvm/versions/node/v18.17.0/bin/pm2 restart app"